CREATE TRIGGER trg_tickets_before_update
BEFORE UPDATE ON tickets
FOR EACH ROW
BEGIN
  IF NEW.status IN ('RESOLVED', 'CANCELLED') AND OLD.status IN ('RESOLVED', 'CANCELLED') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'TICKET_FROZEN';
  END IF;

  IF NEW.status = 'RESOLVED' AND OLD.status <> 'IN_PROGRESS' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'TICKET_INVALID_TRANSITION';
  END IF;

  IF NEW.status = 'CANCELLED' AND OLD.status NOT IN ('OPEN', 'IN_PROGRESS') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'TICKET_INVALID_TRANSITION';
  END IF;

  IF NEW.status = 'IN_PROGRESS' AND (NEW.technician_id IS NULL OR NEW.technician_id = 0) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'TICKET_INVALID_TRANSITION';
  END IF;

  IF OLD.status = 'OPEN' AND NEW.title <> OLD.title THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'TICKET_NOT_EDITABLE';
  END IF;

  IF OLD.status = 'OPEN' AND NEW.description <> OLD.description THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'TICKET_NOT_EDITABLE';
  END IF;
END;
